version: '3.8'

services:
  mysql:
    build: ./database/mysql
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ygo_database
      MYSQL_USER: ygoadmin
      MYSQL_PASSWORD: ygoadmin
      MYSQL_INNODB_FORCE_RECOVERY: 1
    volumes:
      - ./database/mysql/volumes/ygo_volume:/var/lib/mysql
    networks:
      - ygo_network
  
networks:
  ygo_network:
    driver: bridge