import { integer, pgEnum, pgTable, text } from "drizzle-orm/pg-core";

export const rarityEnum = [
  "Common",
  "Rare",
  "Super Rare",
  "Ultra Rare",
] as const;

export const raceEnum = [
  "Beast",
  "Rock",
  "Insect",
  "Machine",
  "Fiend",
  "Warrior",
  "Normal",
  "Dragon",
  "Continuous",
  "Ritual",
  "Aqua",
  "Equip",
  "Spellcaster",
  "Fairy",
  "Reptile",
  "Field",
  "Fish",
  "Dinosaur",
  "Zombie",
  "Plant",
  "Quick-Play",
  "Counter",
  "Winged Beast",
  "Beast-Warrior",
  "Sea Serpent",
  "Pyro",
  "Thunder",
] as const;

export const typeEnum = [
  "Effect Monster",
  "Normal Monster",
  "Flip Effect Monster",
  "Trap Card",
  "Spell Card",
  "Union Effect Monster",
  "Fusion Monster",
  "Ritual Monster",
  "Toon Monster",
  "Ritual Effect Monster",
  "Spirit Monster",
] as const;

export const frameTypeEnum = [
  "effect",
  "normal",
  "trap",
  "spell",
  "fusion",
  "ritual",
] as const;

export const attributeEnum = [
  "EARTH",
  "DARK",
  "LIGHT",
  "WATER",
  "FIRE",
  "WIND",
] as const;

export const archetypeEnum = [
  "Ninja",
  "Dark World",
  "Chaos",
  "Umi",
  "Charmer",
  "Parasite",
  "Monarch",
  "Roid",
  "Archfiend",
  "Mask",
  "Photon",
  "Exodia",
  "Elemental HERO",
  "Herald",
  "Toon",
  "Dark Scorpion",
  "ABC",
  "Guardian",
  "Vampire",
  "Cyber Dragon",
  "Alien",
  "Dark Magician",
  "Destiny HERO",
  "Kuriboh",
  "Anti",
  "Harpie",
  "B.E.S.",
  "Eyes Restrict",
  "Spellbook",
  "Book of",
  "Horus the Black Flame Dragon",
  "Hole",
  "Skull Servant",
  "Fairy",
  "Ancient Gear",
  "The Agent",
  "Magnet Warrior",
  "Amazoness",
  "D.D.",
  "Simorgh",
  "Slime",
  "Armed Dragon",
  "Red-Eyes",
  "Greed",
  "Sphinx",
  "Penguin",
  "Nimble",
  "Demise",
  "Alligator",
  "Gravekeeper's",
  "Djinn",
  "Bonding",
  "Knight",
  "Blue-Eyes",
  "Batteryman",
  "Doriado",
  "Madoor",
  "Gaia The Fierce Knight",
  "Volcanic",
  "Black Luster Soldier",
  "Frog",
  "Battleguard",
  "Cipher",
  "Thunder Dragon",
  "Ojama",
  "Maju",
  "Jinzo",
  "Magician",
  "Nephthys",
  "Rose Dragon",
  "Worm",
  "Majestic",
  "Chrysalis",
  "Grepher",
  "Machina",
  "Spirit Message",
  "Shark",
  "Celtic Guard",
  "Gadget",
  "Silent Magician",
  "Neo-Spacian",
  "Koala",
  "Solemn",
  "Dice",
  "Silent Swordsman",
  "White",
  "Parshath",
  "Earthbound",
  "Gate Guardian",
  "Gandora",
  "Karakuri",
  "Watt",
] as const;

const pgRarity = pgEnum("rarity", rarityEnum);
const pgRace = pgEnum("race", raceEnum);
const pgType = pgEnum("type", typeEnum);
const pgFrameType = pgEnum("frame_type", frameTypeEnum);
const pgAttribute = pgEnum("attribute", attributeEnum);
const pgArchetype = pgEnum("archetype", archetypeEnum);

export const card = pgTable("card", {
  id: integer("id").primaryKey().generatedByDefaultAsIdentity(),
  name: text("name").notNull().unique(),
  gameName: text("game_name").notNull(),
  rarity: pgRarity().notNull(),
  typeline: text("typeline"),
  type: pgType().notNull(),
  humanReadableCardType: text("human_readable_card_type").notNull(),
  frameType: pgFrameType("frame_type").notNull(),
  description: text("description").notNull(),
  race: pgRace().notNull(),
  atk: integer("atk"),
  def: integer("def"),
  level: integer("level"),
  attribute: pgAttribute(),
  archetype: pgArchetype(),
  image: text("image"),
  imageCropped: text("image_cropped"),
});
