spring:
  application:
    name: YuGiOh-Builder
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/ygo_database
    username: ygoadmin
    password: ygoadmin
