version: '3.8'

services:
  mysql:
    build: ./database/mysql
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ff_db
      MYSQL_USER: ffadmin
      MYSQL_PASSWORD: ffadmin
      MYSQL_INNODB_FORCE_RECOVERY: 1
    volumes:
      - ./database/mysql/volumes/ff_volume:/var/lib/mysql
    networks:
      - ff_network
  
networks:
  ff_network:
    driver: bridge