/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PacksImport } from './routes/packs'
import { Route as ListImport } from './routes/list'
import { Route as DuelistsImport } from './routes/duelists'
import { Route as DecksImport } from './routes/decks'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PacksRoute = PacksImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRoute,
} as any)

const ListRoute = ListImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRoute,
} as any)

const DuelistsRoute = DuelistsImport.update({
  id: '/duelists',
  path: '/duelists',
  getParentRoute: () => rootRoute,
} as any)

const DecksRoute = DecksImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksImport
      parentRoute: typeof rootRoute
    }
    '/duelists': {
      id: '/duelists'
      path: '/duelists'
      fullPath: '/duelists'
      preLoaderRoute: typeof DuelistsImport
      parentRoute: typeof rootRoute
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListImport
      parentRoute: typeof rootRoute
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decks': typeof DecksRoute
  '/duelists': typeof DuelistsRoute
  '/list': typeof ListRoute
  '/packs': typeof PacksRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decks': typeof DecksRoute
  '/duelists': typeof DuelistsRoute
  '/list': typeof ListRoute
  '/packs': typeof PacksRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/decks': typeof DecksRoute
  '/duelists': typeof DuelistsRoute
  '/list': typeof ListRoute
  '/packs': typeof PacksRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decks' | '/duelists' | '/list' | '/packs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decks' | '/duelists' | '/list' | '/packs'
  id: '__root__' | '/' | '/decks' | '/duelists' | '/list' | '/packs'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecksRoute: typeof DecksRoute
  DuelistsRoute: typeof DuelistsRoute
  ListRoute: typeof ListRoute
  PacksRoute: typeof PacksRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecksRoute: DecksRoute,
  DuelistsRoute: DuelistsRoute,
  ListRoute: ListRoute,
  PacksRoute: PacksRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/decks",
        "/duelists",
        "/list",
        "/packs"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/decks": {
      "filePath": "decks.tsx"
    },
    "/duelists": {
      "filePath": "duelists.tsx"
    },
    "/list": {
      "filePath": "list.tsx"
    },
    "/packs": {
      "filePath": "packs.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
